Freezing layer 'model.22.dfl.conv.weight'
[34m[1mAMP: [39m[22mrunning Automatic Mixed Precision (AMP) checks with YOLOv8n...
[34m[1mtrain: [39m[22mScanning E:\homework\MVClab\week4\k-street-food\train\labels.cache... 377 images, 21 backgrounds, 0 corrupt: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 377/377 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "E:\Anaconda\envs\federated_learning\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "E:\Anaconda\envs\federated_learning\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "E:\Anaconda\envs\federated_learning\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "E:\Anaconda\envs\federated_learning\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "E:\Anaconda\envs\federated_learning\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "E:\Anaconda\envs\federated_learning\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "E:\Anaconda\envs\federated_learning\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\homework\è³‡è¨Šå®‰å…¨å°Žè«–\pythonProject2\MVCweek4\trainYolo.py", line 7, in <module>
    results = model.train(data="E:\homework\MVClab\week4\k-street-food\data.yaml", epochs=100, imgsz=640, device=[0])
  File "E:\Anaconda\envs\federated_learning\lib\site-packages\ultralytics\engine\model.py", line 674, in train
    self.trainer.train()
  File "E:\Anaconda\envs\federated_learning\lib\site-packages\ultralytics\engine\trainer.py", line 199, in train
    self._do_train(world_size)
  File "E:\Anaconda\envs\federated_learning\lib\site-packages\ultralytics\engine\trainer.py", line 313, in _do_train
    self._setup_train(world_size)
  File "E:\Anaconda\envs\federated_learning\lib\site-packages\ultralytics\engine\trainer.py", line 277, in _setup_train
    self.train_loader = self.get_dataloader(self.trainset, batch_size=batch_size, rank=RANK, mode="train")
  File "E:\Anaconda\envs\federated_learning\lib\site-packages\ultralytics\models\yolo\detect\train.py", line 55, in get_dataloader
    return build_dataloader(dataset, batch_size, workers, shuffle, rank)  # return dataloader
  File "E:\Anaconda\envs\federated_learning\lib\site-packages\ultralytics\data\build.py", line 135, in build_dataloader
    return InfiniteDataLoader(
  File "E:\Anaconda\envs\federated_learning\lib\site-packages\ultralytics\data\build.py", line 39, in __init__
    self.iterator = super().__iter__()
  File "E:\Anaconda\envs\federated_learning\lib\site-packages\torch\utils\data\dataloader.py", line 435, in __iter__
    return self._get_iterator()
  File "E:\Anaconda\envs\federated_learning\lib\site-packages\torch\utils\data\dataloader.py", line 381, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "E:\Anaconda\envs\federated_learning\lib\site-packages\torch\utils\data\dataloader.py", line 1034, in __init__
    w.start()
  File "E:\Anaconda\envs\federated_learning\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "E:\Anaconda\envs\federated_learning\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "E:\Anaconda\envs\federated_learning\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "E:\Anaconda\envs\federated_learning\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "E:\Anaconda\envs\federated_learning\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "E:\Anaconda\envs\federated_learning\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.
        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:
            if __name__ == '__main__':
                freeze_support()
                ...
        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
[34m[1mAMP: [39m[22mchecks passed âœ…
